# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/streamer/Code/Milky_Linux_OSD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/streamer/Code/Milky_Linux_OSD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/streamer/Code/Milky_Linux_OSD/CMakeFiles /home/streamer/Code/Milky_Linux_OSD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/streamer/Code/Milky_Linux_OSD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named milky_osd

# Build rule for target.
milky_osd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 milky_osd
.PHONY : milky_osd

# fast build rule for target.
milky_osd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/build
.PHONY : milky_osd/fast

src/audio/capture.o: src/audio/capture.c.o
.PHONY : src/audio/capture.o

# target to build an object file
src/audio/capture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/capture.c.o
.PHONY : src/audio/capture.c.o

src/audio/capture.i: src/audio/capture.c.i
.PHONY : src/audio/capture.i

# target to preprocess a source file
src/audio/capture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/capture.c.i
.PHONY : src/audio/capture.c.i

src/audio/capture.s: src/audio/capture.c.s
.PHONY : src/audio/capture.s

# target to generate assembly for a file
src/audio/capture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/capture.c.s
.PHONY : src/audio/capture.c.s

src/audio/energy.o: src/audio/energy.c.o
.PHONY : src/audio/energy.o

# target to build an object file
src/audio/energy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/energy.c.o
.PHONY : src/audio/energy.c.o

src/audio/energy.i: src/audio/energy.c.i
.PHONY : src/audio/energy.i

# target to preprocess a source file
src/audio/energy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/energy.c.i
.PHONY : src/audio/energy.c.i

src/audio/energy.s: src/audio/energy.c.s
.PHONY : src/audio/energy.s

# target to generate assembly for a file
src/audio/energy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/energy.c.s
.PHONY : src/audio/energy.c.s

src/audio/kiss_fft/kiss_fft.o: src/audio/kiss_fft/kiss_fft.c.o
.PHONY : src/audio/kiss_fft/kiss_fft.o

# target to build an object file
src/audio/kiss_fft/kiss_fft.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/kiss_fft/kiss_fft.c.o
.PHONY : src/audio/kiss_fft/kiss_fft.c.o

src/audio/kiss_fft/kiss_fft.i: src/audio/kiss_fft/kiss_fft.c.i
.PHONY : src/audio/kiss_fft/kiss_fft.i

# target to preprocess a source file
src/audio/kiss_fft/kiss_fft.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/kiss_fft/kiss_fft.c.i
.PHONY : src/audio/kiss_fft/kiss_fft.c.i

src/audio/kiss_fft/kiss_fft.s: src/audio/kiss_fft/kiss_fft.c.s
.PHONY : src/audio/kiss_fft/kiss_fft.s

# target to generate assembly for a file
src/audio/kiss_fft/kiss_fft.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/kiss_fft/kiss_fft.c.s
.PHONY : src/audio/kiss_fft/kiss_fft.c.s

src/audio/sound.o: src/audio/sound.c.o
.PHONY : src/audio/sound.o

# target to build an object file
src/audio/sound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/sound.c.o
.PHONY : src/audio/sound.c.o

src/audio/sound.i: src/audio/sound.c.i
.PHONY : src/audio/sound.i

# target to preprocess a source file
src/audio/sound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/sound.c.i
.PHONY : src/audio/sound.c.i

src/audio/sound.s: src/audio/sound.c.s
.PHONY : src/audio/sound.s

# target to generate assembly for a file
src/audio/sound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/audio/sound.c.s
.PHONY : src/audio/sound.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/main.c.s
.PHONY : src/main.c.s

src/preset.o: src/preset.c.o
.PHONY : src/preset.o

# target to build an object file
src/preset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/preset.c.o
.PHONY : src/preset.c.o

src/preset.i: src/preset.c.i
.PHONY : src/preset.i

# target to preprocess a source file
src/preset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/preset.c.i
.PHONY : src/preset.c.i

src/preset.s: src/preset.c.s
.PHONY : src/preset.s

# target to generate assembly for a file
src/preset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/preset.c.s
.PHONY : src/preset.c.s

src/signal.o: src/signal.c.o
.PHONY : src/signal.o

# target to build an object file
src/signal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/signal.c.o
.PHONY : src/signal.c.o

src/signal.i: src/signal.c.i
.PHONY : src/signal.i

# target to preprocess a source file
src/signal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/signal.c.i
.PHONY : src/signal.c.i

src/signal.s: src/signal.c.s
.PHONY : src/signal.s

# target to generate assembly for a file
src/signal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/signal.c.s
.PHONY : src/signal.c.s

src/video.o: src/video.c.o
.PHONY : src/video.o

# target to build an object file
src/video.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video.c.o
.PHONY : src/video.c.o

src/video.i: src/video.c.i
.PHONY : src/video.i

# target to preprocess a source file
src/video.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video.c.i
.PHONY : src/video.c.i

src/video.s: src/video.c.s
.PHONY : src/video.s

# target to generate assembly for a file
src/video.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video.c.s
.PHONY : src/video.c.s

src/video/bitdepth.o: src/video/bitdepth.c.o
.PHONY : src/video/bitdepth.o

# target to build an object file
src/video/bitdepth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/bitdepth.c.o
.PHONY : src/video/bitdepth.c.o

src/video/bitdepth.i: src/video/bitdepth.c.i
.PHONY : src/video/bitdepth.i

# target to preprocess a source file
src/video/bitdepth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/bitdepth.c.i
.PHONY : src/video/bitdepth.c.i

src/video/bitdepth.s: src/video/bitdepth.c.s
.PHONY : src/video/bitdepth.s

# target to generate assembly for a file
src/video/bitdepth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/bitdepth.c.s
.PHONY : src/video/bitdepth.c.s

src/video/blur.o: src/video/blur.c.o
.PHONY : src/video/blur.o

# target to build an object file
src/video/blur.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/blur.c.o
.PHONY : src/video/blur.c.o

src/video/blur.i: src/video/blur.c.i
.PHONY : src/video/blur.i

# target to preprocess a source file
src/video/blur.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/blur.c.i
.PHONY : src/video/blur.c.i

src/video/blur.s: src/video/blur.c.s
.PHONY : src/video/blur.s

# target to generate assembly for a file
src/video/blur.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/blur.c.s
.PHONY : src/video/blur.c.s

src/video/draw.o: src/video/draw.c.o
.PHONY : src/video/draw.o

# target to build an object file
src/video/draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/draw.c.o
.PHONY : src/video/draw.c.o

src/video/draw.i: src/video/draw.c.i
.PHONY : src/video/draw.i

# target to preprocess a source file
src/video/draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/draw.c.i
.PHONY : src/video/draw.c.i

src/video/draw.s: src/video/draw.c.s
.PHONY : src/video/draw.s

# target to generate assembly for a file
src/video/draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/draw.c.s
.PHONY : src/video/draw.c.s

src/video/effects/chaser.o: src/video/effects/chaser.c.o
.PHONY : src/video/effects/chaser.o

# target to build an object file
src/video/effects/chaser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/effects/chaser.c.o
.PHONY : src/video/effects/chaser.c.o

src/video/effects/chaser.i: src/video/effects/chaser.c.i
.PHONY : src/video/effects/chaser.i

# target to preprocess a source file
src/video/effects/chaser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/effects/chaser.c.i
.PHONY : src/video/effects/chaser.c.i

src/video/effects/chaser.s: src/video/effects/chaser.c.s
.PHONY : src/video/effects/chaser.s

# target to generate assembly for a file
src/video/effects/chaser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/effects/chaser.c.s
.PHONY : src/video/effects/chaser.c.s

src/video/effects/tunnel.o: src/video/effects/tunnel.c.o
.PHONY : src/video/effects/tunnel.o

# target to build an object file
src/video/effects/tunnel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/effects/tunnel.c.o
.PHONY : src/video/effects/tunnel.c.o

src/video/effects/tunnel.i: src/video/effects/tunnel.c.i
.PHONY : src/video/effects/tunnel.i

# target to preprocess a source file
src/video/effects/tunnel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/effects/tunnel.c.i
.PHONY : src/video/effects/tunnel.c.i

src/video/effects/tunnel.s: src/video/effects/tunnel.c.s
.PHONY : src/video/effects/tunnel.s

# target to generate assembly for a file
src/video/effects/tunnel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/effects/tunnel.c.s
.PHONY : src/video/effects/tunnel.c.s

src/video/palette.o: src/video/palette.c.o
.PHONY : src/video/palette.o

# target to build an object file
src/video/palette.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/palette.c.o
.PHONY : src/video/palette.c.o

src/video/palette.i: src/video/palette.c.i
.PHONY : src/video/palette.i

# target to preprocess a source file
src/video/palette.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/palette.c.i
.PHONY : src/video/palette.c.i

src/video/palette.s: src/video/palette.c.s
.PHONY : src/video/palette.s

# target to generate assembly for a file
src/video/palette.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/palette.c.s
.PHONY : src/video/palette.c.s

src/video/transform.o: src/video/transform.c.o
.PHONY : src/video/transform.o

# target to build an object file
src/video/transform.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/transform.c.o
.PHONY : src/video/transform.c.o

src/video/transform.i: src/video/transform.c.i
.PHONY : src/video/transform.i

# target to preprocess a source file
src/video/transform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/transform.c.i
.PHONY : src/video/transform.c.i

src/video/transform.s: src/video/transform.c.s
.PHONY : src/video/transform.s

# target to generate assembly for a file
src/video/transform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/milky_osd.dir/build.make CMakeFiles/milky_osd.dir/src/video/transform.c.s
.PHONY : src/video/transform.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... milky_osd"
	@echo "... src/audio/capture.o"
	@echo "... src/audio/capture.i"
	@echo "... src/audio/capture.s"
	@echo "... src/audio/energy.o"
	@echo "... src/audio/energy.i"
	@echo "... src/audio/energy.s"
	@echo "... src/audio/kiss_fft/kiss_fft.o"
	@echo "... src/audio/kiss_fft/kiss_fft.i"
	@echo "... src/audio/kiss_fft/kiss_fft.s"
	@echo "... src/audio/sound.o"
	@echo "... src/audio/sound.i"
	@echo "... src/audio/sound.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/preset.o"
	@echo "... src/preset.i"
	@echo "... src/preset.s"
	@echo "... src/signal.o"
	@echo "... src/signal.i"
	@echo "... src/signal.s"
	@echo "... src/video.o"
	@echo "... src/video.i"
	@echo "... src/video.s"
	@echo "... src/video/bitdepth.o"
	@echo "... src/video/bitdepth.i"
	@echo "... src/video/bitdepth.s"
	@echo "... src/video/blur.o"
	@echo "... src/video/blur.i"
	@echo "... src/video/blur.s"
	@echo "... src/video/draw.o"
	@echo "... src/video/draw.i"
	@echo "... src/video/draw.s"
	@echo "... src/video/effects/chaser.o"
	@echo "... src/video/effects/chaser.i"
	@echo "... src/video/effects/chaser.s"
	@echo "... src/video/effects/tunnel.o"
	@echo "... src/video/effects/tunnel.i"
	@echo "... src/video/effects/tunnel.s"
	@echo "... src/video/palette.o"
	@echo "... src/video/palette.i"
	@echo "... src/video/palette.s"
	@echo "... src/video/transform.o"
	@echo "... src/video/transform.i"
	@echo "... src/video/transform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

